### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by ansco11** [eiffel-wrap-c/WrapC#41]
https://github.com/eiffel-wrap-c/WrapC/blob/master/doc/developer/Readme.md#build_examples

In the documentation for the simple example:

```
cd ${WRAP_C}/examples/simple/library
geant install
```

The command fails with no target called 'install', but geant wrap_c works.

**Comment by ansco11** [comment]
Attempting to build examples/simple/example/hello_world fails on ISE Eiffel 19.08

$ geant compile
Degree 6: 0/0/0 0:0:0.025
Degree 5: 0/0/0 0:0:0.210
[GVKBU-1] class REFLECTOR (486,2): unknown built-in routine `c_set_dynamic_type' in class REFLECTOR.
----
[GVKBU-1] class REFLECTOR (478,2): unknown built-in routine `c_new_type_instance_of' in class REFLECTOR.
----
[GVKBU-1] class REFLECTOR (468,2): unknown built-in routine `c_new_tuple_instance_of' in class REFLECTOR.
----
[GVKBU-1] class REFLECTOR (456,2): unknown built-in routine `c_new_instance_of' in class REFLECTOR.
----
[GVKBU-1] class REFLECTOR (416,2): unknown built-in routine `field_count_of_type' in class REFLECTOR.
----
[GVKBU-1] class REFLECTOR (233,2): unknown built-in routine `is_tuple_type' in class REFLECTOR.
----
[GVKBU-1] class REFLECTOR (220,2): unknown built-in routine `is_special_type' in class REFLECTOR.
----
[GVKBU-1] class REFLECTOR (209,2): unknown built-in routine `is_special_any_type' in class REFLECTOR.
----
Degree 4: 0/0/0 0:0:0.090
Degree 3: 0/0/0 0:0:0.139
Degree -2: 0/0/0 0:0:0.042
Total Time: 0/0/0 0:0:0.507

**Comment by jvelilla** [comment]
I've updated the documentation
```
cd ${WRAP_C}/examples/simple/library
geant wrap_c`
```
To run the example `geant` is not needed anymore
just do

```
   estudio system.ecf
   then compile
   then run
```

Please let me know if this helps.
